name: Java CI for IntelliJ Plugin

on:
  push:  # Run pipeline on push to any branch
    branches:
      - '**'  # '**' matches all branches
  pull_request:
    branches:
      - '**'  # Also run pipeline on any pull request to any branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # or 'zulu' as an alternative JVM distribution
          java-version: '17'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Step 4: Validate Gradle Wrapper
      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version

      # Step 5: Build the project
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # Step 6: Run tests
      - name: Run tests
        run: ./gradlew test --no-daemon

      # Step 7: Package the plugin
      - name: Build plugin
        run: ./gradlew buildPlugin

      # Step 8: Upload build artifacts (optional)
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-artifact
          path: build/distributions/*.zip
