name: Java CI for IntelliJ Plugin

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Step 4: Set execute permission for Gradle wrapper
      - name: Set execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Step 5: Validate and update Gradle Wrapper
      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 7.6

      # Step 6: Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Step 7: Run tests
      - name: Run tests
        run: ./gradlew test

      # Step 8: Package the plugin
      - name: Build plugin
        run: ./gradlew buildPlugin

      # Step 9: Upload build artifacts (optional)
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-artifact
          path: build/distributions/*.zip